"""add_tips_pages_and_blocks_table

Revision ID: a4e278391af4
Revises: 
Create Date: 2025-11-15 05:57:47.351370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e278391af4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.String(length=64), nullable=False, comment='Unique identifier for the trip in the URL'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Title of the trip'),
    sa.Column('detail', sa.Text(), nullable=False, comment='Detailed description of the trip'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_url_id'), 'trips', ['url_id'], unique=True)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False, comment='Foreign key to the associated trip'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Title of the page'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_trip_id'), 'pages', ['trip_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Title of the block'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='Start time of the block(UTC)'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='End time of the block(UTC)'),
    sa.Column('page_id', sa.Integer(), nullable=False, comment='Foreign key to the associated page'),
    sa.Column('detail', sa.Text(), nullable=False, comment='Detailed description of the block'),
    sa.Column('block_type', sa.String(length=100), nullable=False, comment='Type of the block defined in app as enum'),
    sa.Column('transportation_type', sa.String(length=100), nullable=True, comment='Type of transportation'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_page_id'), 'blocks', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocks_page_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_pages_trip_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_trips_url_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
