"""make_detail_nullable_in_trips_and_blocks

Revision ID: ee1707608398
Revises: a4e278391af4
Create Date: 2026-03-08 12:50:10.593315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1707608398'
down_revision: Union[str, Sequence[str], None] = 'a4e278391af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'detail',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Detailed description of the block')
    op.alter_column('trips', 'detail',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Detailed description of the trip')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'detail',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Detailed description of the trip')
    op.alter_column('blocks', 'detail',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Detailed description of the block')
    # ### end Alembic commands ###
