"""add_locations_table_and_block_location_fks

Revision ID: 60339fc50f4f
Revises: ee1707608398
Create Date: 2026-04-14 19:10:02.032075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60339fc50f4f'
down_revision: Union[str, Sequence[str], None] = 'ee1707608398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=True, comment='Google Places API の place_id'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='場所名'),
    sa.Column('address', sa.Text(), nullable=True, comment='住所'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='緯度'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='経度'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_google_place_id'), 'locations', ['google_place_id'], unique=False)
    op.add_column('blocks', sa.Column('location_id', sa.Integer(), nullable=True, comment='場所（Schedule: この場所, Transportation: 出発地）'))
    op.add_column('blocks', sa.Column('destination_location_id', sa.Integer(), nullable=True, comment='目的地（Transportationのみ使用）'))
    op.create_index(op.f('ix_blocks_destination_location_id'), 'blocks', ['destination_location_id'], unique=False)
    op.create_index(op.f('ix_blocks_location_id'), 'blocks', ['location_id'], unique=False)
    op.create_foreign_key('fk_blocks_location_id', 'blocks', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_blocks_destination_location_id', 'blocks', 'locations', ['destination_location_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('ck_blocks_destination_only_for_move', 'blocks', "block_type = 'move' OR destination_location_id IS NULL")
    op.create_check_constraint('ck_blocks_transportation_type_only_for_move', 'blocks', "transportation_type IS NULL OR block_type = 'move'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_blocks_transportation_type_only_for_move', 'blocks', type_='check')
    op.drop_constraint('ck_blocks_destination_only_for_move', 'blocks', type_='check')
    op.drop_constraint('fk_blocks_destination_location_id', 'blocks', type_='foreignkey')
    op.drop_constraint('fk_blocks_location_id', 'blocks', type_='foreignkey')
    op.drop_index(op.f('ix_blocks_location_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_destination_location_id'), table_name='blocks')
    op.drop_column('blocks', 'destination_location_id')
    op.drop_column('blocks', 'location_id')
    op.drop_index(op.f('ix_locations_google_place_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
