name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps
      
      - name: Format check
        run: npm run format:check

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps
      
      - name: Lint check
        run: npm run lint:check

  build:
    runs-on: ubuntu-latest
    needs: [format-check, lint-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps
      
      - name: Build
        run: npm run build